{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "table-planner.fullname" . }}-backend
  labels:
    {{- include "table-planner.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "table-planner.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
